services:
  - type: web
    name: carbotrackr-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: FAT_SECRET_CONSUMER_KEY
        sync: false
      - key: FAT_SECRET_CONSUMER_SECRET
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_API_KEY
        sync: false

